# Generated by Django 2.2.8 on 2019-12-06 15:52

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('price', models.PositiveIntegerField()),
                ('cashback', models.PositiveIntegerField()),
                ('full_desc', models.TextField()),
                ('tech', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photo_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
            ],
        ),
    ]
